### ISSUE TITLE
Eslint errors

### ISSUE THREAD

**Issue by VictorBaudot** [leksster/nextjs6-graphql-client-tutorial#24]
Hello,
Is it normal that I get a lot of Eslint errors in 
pages/_app.js & pages/_document.js ?
I'm using vscode with ESLint extension from Dirk Baeumer

![image](https://user-images.githubusercontent.com/33088396/45928250-e83e2880-bf40-11e8-8773-117ce2d07eae.png)

**Comment by VictorBaudot** [comment]
Was caused by my prettier extension

**Comment by VictorBaudot** [comment]
In fact not all eslint errors where caused by prettier
I still get those:

![image](https://user-images.githubusercontent.com/33088396/45930042-71158e00-bf5a-11e8-9e4d-4f21af1c9f32.png)

**Comment by leksster** [comment]
Hello @VictorBaudot. Thanks for reporting this.

I've fixed these errors and added TravisCI integration with eslint and jest scripts to avoid errors like these in the future. Changes already in `master` branch.

**Comment by VictorBaudot** [comment]
Ok nice @leksster, I opened a pull request to fix a few other errors
